2024-12-09 21:29:46,750 - INFO - Starting mass conservation analysis
2024-12-09 21:29:50,113 - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
2024-12-09 21:29:50,173 - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 113] No route to host
2024-12-09 21:29:53,176 - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
2024-12-09 21:29:53,177 - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
2024-12-09 21:29:53,183 - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd3853940>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:53,186 - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd3853c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:53,189 - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd38a80a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:53,192 - WARNING - Compute Engine Metadata server unavailable on attempt 4 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd3853dc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:53,195 - WARNING - Compute Engine Metadata server unavailable on attempt 5 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd3853a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:56,819 - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
2024-12-09 21:29:56,821 - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
2024-12-09 21:29:56,825 - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
2024-12-09 21:29:56,828 - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
2024-12-09 21:29:56,893 - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 113] No route to host
2024-12-09 21:29:56,893 - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 113] No route to host
2024-12-09 21:29:56,893 - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 113] No route to host
2024-12-09 21:29:56,893 - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 113] No route to host
2024-12-09 21:29:59,896 - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
2024-12-09 21:29:59,896 - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
2024-12-09 21:29:59,897 - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
2024-12-09 21:29:59,897 - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
2024-12-09 21:29:59,897 - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
2024-12-09 21:29:59,897 - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
2024-12-09 21:29:59,897 - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
2024-12-09 21:29:59,897 - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
2024-12-09 21:29:59,906 - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd2f41780>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:59,906 - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd2f41690>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:59,906 - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd2f41a50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:59,907 - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd2f41960>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:59,911 - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd2f41960>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:59,911 - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd2f41a50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:59,912 - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd2f41de0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:59,912 - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd2f41cf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:59,916 - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd2f42230>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:59,916 - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd2f41f90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:59,916 - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd2f41ea0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:59,917 - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd2f42320>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:59,921 - WARNING - Compute Engine Metadata server unavailable on attempt 4 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd2f42770>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:59,921 - WARNING - Compute Engine Metadata server unavailable on attempt 4 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd2f424d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:59,922 - WARNING - Compute Engine Metadata server unavailable on attempt 4 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd2f42860>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:59,922 - WARNING - Compute Engine Metadata server unavailable on attempt 4 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd2f423e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:59,925 - WARNING - Compute Engine Metadata server unavailable on attempt 5 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd2f42a10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:59,925 - WARNING - Compute Engine Metadata server unavailable on attempt 5 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd2f42cb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:59,926 - WARNING - Compute Engine Metadata server unavailable on attempt 5 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd2f42da0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-12-09 21:29:59,926 - WARNING - Compute Engine Metadata server unavailable on attempt 5 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd2f42920>: Failed to establish a new connection: [Errno -2] Name or service not known'))
